### ISSUE TITLE
Multi-layer vector tiles schema

### ISSUE THREAD

**Issue by aaime** [opengeospatial/OGC-API-Tiles#18]
During Vector Tiles Pilot 2 we found that some implementations want to deliver multi-layer Mapbox vector tiles using the Tiles API, and would like to have a good way to advertise the structure of the layers found in the vector tiles, and their attributes, for cases where these are available, and stable across tiles.

One possible approach would be to first deliver each layer as a collection, each collection having a describedBy link,
and gathering the multi-layer vector tiles via the "tiles from more than one collection" requirement class.
A client needing a schema would then scan over the collections about to be requested and gather the schemas.
This is however not ideal in all scenarios:
* One might not want to make the single collections available
* One might not want to expose the "tiles from more than one collection" extension 
* JSON schema is not native to the MVT world

Another possible approach we'd like to explore is to serve multi-layer MVT out of a single collection in the Tiles API, and having a single "describedBy" link reporting the structure of the multi-layer vector tile, possibly as a "TileJSON" V3 document: 
https://github.com/mapbox/tilejson-spec/tree/3.0/3.0.0
(unlike version 2.2, this document contains a list of layers and attributes, among other things).

Also, when multiple tile encodings are available, it would be useful to have a "native description" of each, e.g., MVT could use TileJSON while GeoJSON tiles would use JSON schema instead (thanks @cportele for pointing this out).

It would be useful if the Tiles API specification provided some direction in this regard.

**Comment by jyutzler** [comment]
The more I look at this, the more I like it.

**Comment by joanma747** [comment]
I trying to rethink the OGC API Tiles as a true building block and not as a service. By doing so, "tiles" becomes a "transformation" of a resource into a set of tiles. The type of resource does not matter anymore an the only requirement will be that the resource has some geospatial component.

This does not change the way you deal with a "collection":
\collections\{collectionId}\tiles...
But I could not care less if collections are hierarchical or not:
\cartography\topography\collections\buildings\tiles...
or if it is a coverage
\coverage\temperature\tiles...
or images in the image API.
\images\sentinel2\tiles...

Now: HOW TO DEAL with multiple resources (collections) in a tile (multitiles)?
It occurs to me that we could take advantage of one concept in TileJSON: The "vector_layers". Actually, this has nothing to do with tiles. It is just a set of layers one on top of the other. Actually it does not matter if it is vector or raster data. Lets generalize con concept to any kind of geospatial resource and call it an "stack" (or if you prefer an "overlay"). Let's accept that an "stack" is a resource (that is composed by a "stack" of heterogeneous resources). 

I propose the following:
\stacks\{stackId}
A response to a GET request will give you a list of links to the actual resources composing the "stack" of layers:
GET \stacks\topographic
response:
"links": [
    {
      "href": "http://data.example.org/collections/buildings,
      "rel": "item",
      "type": "application/json",
    },
    {
      "href": "http://data.example.org/collections/roads,
      "rel": "item",
      "type": "application/json",
    }
]

Then you can apply tiles to it and you will get a tile from multiple collections:
\stacks\{stackId}\tiles

Since the service controls what is in the stack, it is not possible that the client requests over-complicated things. In addition, stacks can be cached easily because they are more predictable that the previous proposal \tiles?collections=. Stacks are designed in the server side to support a predefined list of tilematrixsets (in \tiles?collections= it is more difficult to know the tilematrixsets supported as the collectionIds can support conflicting tilematrixsets).

Another good think is that now we could do:
\stacks\{stackId}\map?width=500...
to get a map of the stack.

My proposal is to go for "stacks" and deprecate the idea of \tiles?collections= in the OGC API Tiles.

**Comment by joanma747** [comment]
And, if as a client, you want a new combination (a new stack), just POST a new resource into \stacks and, if the server likes it, you will get a new stackId for the new stack.

**Comment by cportele** [comment]
I do not understand the need for the "stack" concept. 

If you can have a Tile Sets resource under any resource that represents a data source, then the tiles will contain data from that data source. What is then needed is a way to express the contents of the tiles so that clients can understand it. For MVT there are good reasons to at least consider using tilejson as-is for this, because of the existing tooling. For other tile encodings other metadata may be more appropriate.

**Comment by joanma747** [comment]
> What is then needed is a way to express the contents of the tiles so that clients can understand it.
Exactly. This is what I'm talking about.

In Testbed 15 there was a requirement to support tiles from more than one collection. Tilejson is proposing vector-layers that allows for that. But there are other things a part from "features" so I though it could be good to generalize it.

tilejson is mixing at least 3 concepts in a single file: definition of the tile templates, limits on the tilematrixsets and vector-layers. IMHO not a very modular approach.

Everybody is free to use tilejson as it is in any API. I'm sure it works for Google Mercator (only). It is also compatible with OGC concepts (except for the schema:tms not suported in the TileMatrixSet). Is this what we want to adopt for OGC API Tiles?. IMHO it is not enough but we can learn from some parts of it.

**Comment by aaime** [comment]
Creating stacks from the client side might be interesting for some advanced use cases, but too complicated for the common one. The case I'm referring to, widely available on the internet now, is delivering a multi-layer base map (e.g. pngs, e.g. https://www.openstreetmap.org) , or a multi-layer vector tile map (e.g., openmaptiles, https://www.maptiler.com/maps) as a single collection. 

These collections can be described as non subdivisible units, can have a schema of their own, can have metadata of their own, the composing layers underneath may not even be visible or advertised (openstreemap). 

The "XYZ tile layer" is a case that should be supported by the OGC API in a simple way, with minimal extra requirements compared to the random offerings already available on the net.

**Comment by joanma747** [comment]
From OGC API features (section 7.1. Overview):
"Each feature in a dataset is part of exactly one collection."
Conclusion: An aggregation of collections is not a collection by definition. This is way I'm forced to define a "stack" (a.k.a vector-layer) to be able to provide tiles of a multi-layer base map.

**Comment by aaime** [comment]
In the context of a OGC API Features that is correct. I've implemented OGC API Tiles as a stand alone service, free of those restrictions. Please don't restrict it to be just a building block of other services, while useful, it's should not be the only way to implement it.

**Comment by cportele** [comment]
> Conclusion: An aggregation of collections is not a collection by definition. This is way I'm forced to define a "stack" (a.k.a vector-layer) to be able to provide tiles of a multi-layer base map.

And even in the context of the Features resources, you can still have /tiles as a top-level resource without the need for stacks. 

In my view, one implication of an approach that defines the Tile Sets resource as a "plugable" resource is that some details may depend on the characteristics of the parent resource and are best specified in the specification of the parent resource.

**Comment by jeffharrison** [comment]
The approach outlined by Andrea seems very rational...

'Another possible approach we'd like to explore is to serve multi-layer MVT out of a single collection in the Tiles API, and having a single "describedBy" link reporting the structure of the multi-layer vector tile, possibly as a "TileJSON" V3 document:
https://github.com/mapbox/tilejson-spec/tree/3.0/3.0.0
(unlike version 2.2, this document contains a list of layers and attributes, among other things).

Also, when multiple tile encodings are available, it would be useful to have a "native description" of each, e.g., MVT could use TileJSON while GeoJSON tiles would use JSON schema instead (thanks @cportele for pointing this out).'

I agree that it would be useful if the Tiles API specification provided some direction in this regard.

**Comment by jeffharrison** [comment]
(From recent email dialog)

...In addition to the comments above, for vector tiles we need concepts equivalent to

1) a multi-layer tile which provides multiple feature types in a single vector tile 

2) a single-layer tile which provides a single feature type in a single vector tile

Best Regards,
Jeff

**Comment by ghobona** [comment]
This issue has been addressed by PR https://github.com/opengeospatial/OGC-API-Tiles/pull/32
